version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=scalewaywebsite
      - POSTGRES_USER=jaycee
      - POSTGRES_PASSWORD=jaycee
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432

  web:
    build: ./web
    image: scalewaywebsite
    restart: unless-stopped
    depends_on:
      - db
    command: /usr/local/bin/uwsgi --ini /jclock.co.uk/uwsgi_conf.ini --uid www-data --gid www-data
    volumes:
      - ./web/uwsgi_conf.ini:/jclock.co.uk/uwsgi_conf.ini
      - /var/www-data/ScalewayWebsite/:/var/www-data/ScalewayWebsite/
    expose:
      - 8080

  parse-dashboard:
    image: parse-dashboard
    build: ./parse-dashboard
    restart: unless-stopped
    expose:
      - 4040
    depends_on:
      - parse-server
    volumes:
      - ./parse-dashboard/config.json:/parse-dashboard/config.json 
    command: /usr/local/bin/parse-dashboard --mountPath=/dashboard --allowInsecureHTTP=1 --appId=tagalong --masterKey=tagalong
    environment:
      - PARSE_DASHBOARD_SERVER_URL=http://localhost/parse/
      - PARSE_DASHBOARD_USER_PASSWORD=jaycee
      - PARSE_DASHBOARD_USER_ID=jaycee

  parse-server:
    image: parse-server
    build: ./parse-server
    restart: unless-stopped
    expose:
      - 1337
    depends_on: 
      - db
    volumes:
      - ./parse-server/config.json:/parse-server/config.json
    command: /usr/local/bin/parse-server /parse-server/config.json 
    environment:
      - PARSE_PUBLIC_SERVER_URL=http://proxy/parse/
      - PARSE_SERVER_URL=http://localhost:1337/parse/
      - VERBOSE=1

  #gitlab:
    #image: gitlab
    #build: ./gitlab
    #restart: unless-stopped
    #expose:
      #- 443
      #- 80
      #- 22
    #environment:
      #GITLAB_OMNIBUS_CONFIG: |
       #external_url 'http://localhost'
       #letsencrypt['enabled'] = false
       #nginx['listen_port'] = 80
       #nginx['listen_https'] = false
       #nginx['proxy_set_headers'] = {
         #"X-Forwarded-Proto" => "$$schema",
         #"X-Forwarded-Ssl" => "on",
         #"Host" => "localhost",
         #"X-Real-IP" => "$$remote_addr",
         #"X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
         #"Upgrade" => "$$http_upgrade",
         #"Connection" => "$$connection_upgrade"
    #volumes:
      #- /var/www-data/gitlab/config:/etc/gitlab
      #- /var/www-data/gitlab/logs:/var/log/gitlab
      #- /var/www-data/gitlab/data/:/var/opt/gitlab

  #syncthing:
    #image: syncthing
    #build: ./syncthing
    #restart: unless-stopped
    #expose:
      #- 8384
      #- 22000
      #- 21027/udp
    #volumes:
      #- /mnt/backup/SyncthingBackup/:/backup
    #command: /usr/bin/syncthing -gui-address http://localhost:8384/

  proxy:
    image: proxy
    build: ./proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/uwsgi_params:/etc/nginx/uwsgi_params
      - /etc/letsencrypt/live/jclock.co.uk/privkey.pem:/etc/nginx/conf.d/key.pem
      - /etc/letsencrypt/live/jclock.co.uk/fullchain.pem:/etc/nginx/conf.d/cert.pem
      - /var/www-data/ScalewayWebsite/:/var/www-data/ScalewayWebsite/
    command: "bash -c '/usr/sbin/nginx -g \"daemon off;\"'"

volumes:
  postgres_data:
