version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=scalewaywebsite
      - POSTGRES_USER=jaycee
      - POSTGRES_PASSWORD=jaycee
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
  web:
    build: ./web
    image: scalewaywebsite
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      - db
    command: /usr/local/bin/uwsgi --ini /jclock.co.uk/uwsgi_conf.ini --uid www-data --gid www-data
    links:
      - db
    volumes:
      - ./web/uwsgi_conf.ini:/jclock.co.uk/uwsgi_conf.ini
      - /var/www-data/ScalewayWebsite/:/var/www-data/ScalewayWebsite/
  parse:
    image: parse-server
    build: ./parse
    restart: unless-stopped
    expose:
      - 1337
    links:
      - db
    depends_on: 
      - db
    volumes:
      - ./parse/config.json:/parse-server/config.json
    command: /usr/local/bin/parse-server /parse-server/config.json
  proxy:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "1337:1337"
    links:
      - parse
      - web
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/uwsgi_params:/etc/nginx/uwsgi_params
      - ./proxy/key.pem:/etc/nginx/conf.d/key.pem
      - ./proxy/cert.pem:/etc/nginx/conf.d/cert.pem
      - /var/www-data/ScalewayWebsite/:/var/www-data/ScalewayWebsite/
    command: "bash -c '/usr/sbin/nginx -g \"daemon off;\"'"

volumes:
  postgres_data:
